**Encoading techniques**

**1 Label Encoading**

In [3]:
# Import the libraies 
import pandas as pd
import numpy as np

In [10]:
data = {'color':['Red','Green','Blue'],'RGB_value':[30,89,48],'Damage_calues':['No','Yes','No']}

In [18]:
# import the dataset and feature scaling
dataset = pd.DataFrame(data)
x = dataset.iloc[:,:2].values
y = dataset.iloc[:,-1].values

In [19]:
print(x)

[['Red' 30]
 ['Green' 89]
 ['Blue' 48]]


In [20]:
print(y)

['No' 'Yes' 'No']


In [23]:
# Encoading the Independent Variable x 
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers =[('encoder',OneHotEncoder(),[0])],remainder ='passthrough')
x =np.array(ct.fit_transform(x))

In [24]:
print(x)

[[0.0 0.0 1.0 30]
 [0.0 1.0 0.0 89]
 [1.0 0.0 0.0 48]]


**Red is encoded as [0  0 1] ,, 
Green is encoded as [0 1 0]] ,, 
Blue is encoded as [1 0 0]**

In [25]:
# Encoading the dependent variable y 
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [26]:
print(y)

[0 1 0]


**Yes is encoded as 1 and  
No is encoded as 0**