In [54]:
# Import the libraries 
import pandas as pd 
import numpy as np 

In [55]:
# Import the dataset
dataset = pd.read_csv('50_startups.csv')
x = dataset.iloc[:,:4].values
y = dataset.iloc[:,-1:].values

In [56]:
print(x)

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']
 [131876.9 99814.71 362861.36 'New York']
 [134615.46 147198.87 127716.82 'California']
 [130298.13 145530.06 323876.68 'Florida']
 [120542.52 148718.95 311613.29 'New York']
 [123334.88 108679.17 304981.62 'California']
 [101913.08 110594.11 229160.95 'Florida']
 [100671.96 91790.61 249744.55 'California']
 [93863.75 127320.38 249839.44 'Florida']
 [91992.39 135495.07 252664.93 'California']
 [119943.24 156547.42 256512.92 'Florida']
 [114523.61 122616.84 261776.23 'New York']
 [78013.11 121597.55 264346.06 'California']
 [94657.16 145077.58 282574.31 'New York']
 [91749.16 114175.79 294919.57 'Florida']
 [86419.7 153514.11 0.0 'New York']
 [76253.86 113867.3 298664.47 'California']
 [78389.47 153773.43 299737.29 'New York']
 [73994.56 122782.75 303319.26 'Florida']
 [67532

In [57]:
print(y)

[[192261.83]
 [191792.06]
 [191050.39]
 [182901.99]
 [166187.94]
 [156991.12]
 [156122.51]
 [155752.6 ]
 [152211.77]
 [149759.96]
 [146121.95]
 [144259.4 ]
 [141585.52]
 [134307.35]
 [132602.65]
 [129917.04]
 [126992.93]
 [125370.37]
 [124266.9 ]
 [122776.86]
 [118474.03]
 [111313.02]
 [110352.25]
 [108733.99]
 [108552.04]
 [107404.34]
 [105733.54]
 [105008.31]
 [103282.38]
 [101004.64]
 [ 99937.59]
 [ 97483.56]
 [ 97427.84]
 [ 96778.92]
 [ 96712.8 ]
 [ 96479.51]
 [ 90708.19]
 [ 89949.14]
 [ 81229.06]
 [ 81005.76]
 [ 78239.91]
 [ 77798.83]
 [ 71498.49]
 [ 69758.98]
 [ 65200.33]
 [ 64926.08]
 [ 49490.75]
 [ 42559.73]
 [ 35673.41]
 [ 14681.4 ]]


In [58]:
# Encoding Independent variable 
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[3])],remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [59]:
print(x)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

In [60]:
# Splliting the dataset into training and testing data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [61]:
print(x_train)

[[0.0 1.0 0.0 55493.95 103057.49 214634.81]
 [0.0 0.0 1.0 46014.02 85047.44 205517.64]
 [0.0 1.0 0.0 75328.87 144135.98 134050.07]
 [1.0 0.0 0.0 46426.07 157693.92 210797.67]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 1000.23 124153.04 1903.93]
 [0.0 0.0 1.0 542.05 51743.15 0.0]
 [0.0 0.0 1.0 65605.48 153032.06 107138.38]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [0.0 1.0 0.0 61994.48 115641.28 91131.24]
 [1.0 0.0 0.0 63408.86 129219.61 46085.25]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [1.0 0.0 0.0 23640.93 96189.63 148001.11]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 15505.73 127382.3 35534.17]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [1.0 0.0 0.0 64664.71 139553.16 137962.62]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [1.0 0.0 0.0 28754.33 118546.05 172795.67]
 [1.

In [62]:
print(x_test)

[[0.0 1.0 0.0 66051.52 182645.56 118148.2]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [0.0 1.0 0.0 27892.92 84710.77 164470.71]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 72107.6 127864.55 353183.81]
 [0.0 0.0 1.0 20229.59 65947.93 185265.1]
 [0.0 0.0 1.0 61136.38 152701.92 88218.23]
 [0.0 1.0 0.0 73994.56 122782.75 303319.26]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]]


In [63]:
print(y_train)

[[ 96778.92]
 [ 96479.51]
 [105733.54]
 [ 96712.8 ]
 [124266.9 ]
 [155752.6 ]
 [132602.65]
 [ 64926.08]
 [ 35673.41]
 [101004.64]
 [129917.04]
 [ 99937.59]
 [ 97427.84]
 [126992.93]
 [ 71498.49]
 [118474.03]
 [ 69758.98]
 [152211.77]
 [134307.35]
 [107404.34]
 [156991.12]
 [125370.37]
 [ 78239.91]
 [ 14681.4 ]
 [191792.06]
 [141585.52]
 [ 89949.14]
 [108552.04]
 [156122.51]
 [108733.99]
 [ 90708.19]
 [111313.02]
 [122776.86]
 [149759.96]
 [ 81005.76]
 [ 49490.75]
 [182901.99]
 [192261.83]
 [ 42559.73]
 [ 65200.33]]


In [64]:
print(y_test)

[[103282.38]
 [144259.4 ]
 [146121.95]
 [ 77798.83]
 [191050.39]
 [105008.31]
 [ 81229.06]
 [ 97483.56]
 [110352.25]
 [166187.94]]


In [66]:
# feature scalling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:,1:]=sc.fit_transform(x_train[:,1:])
x_test[:,1:] = sc.transform(x_test[:,1:])

In [67]:
print(x_train)

[[0.0 1.7320508075688774 -0.733799385705343 -0.3500645436227844
  -0.7854710924793271 0.1011968019362538]
 [0.0 -0.5773502691896258 1.3627702877384942 -0.555303187426314
  -1.481174262628151 0.02734979174277092]
 [0.0 1.7320508075688774 -0.733799385705343 0.07935762307586282
  0.8013338146656704 -0.551521323997471]
 [1.0 -0.5773502691896258 -0.733799385705343 -0.5463823849331263
  1.3250581707161837 0.07011683779235604]
 [0.0 1.7320508075688774 -0.733799385705343 0.4348537132854595
  -0.3559866348200946 0.7514851578736048]
 [0.0 1.7320508075688774 -0.733799385705343 1.2694314288195354
  0.855185185174973 0.986031184474382]
 [0.0 1.7320508075688774 -0.733799385705343 1.045250070905001
  1.2807704710942711 0.44039999942558483]
 [0.0 -0.5773502691896258 1.3627702877384942 -1.529843000700978
  0.029420649133439825 -1.6218751012780783]
 [0.0 -0.5773502691896258 1.3627702877384942 -1.5397625087372082
  -2.767672641730695 -1.6372965026688253]
 [0.0 -0.5773502691896258 1.3627702877384942 -0.13

In [68]:
print(x_test)

[[0.0 1.7320508075688774 -0.733799385705343 -0.12149520306216502
  2.2889053032012234 -0.6803228661410794]
 [1.0 -0.5773502691896258 -0.733799385705343 0.6280306007656555
  -1.2206949887864658 0.38557773677354845]
 [0.0 1.7320508075688774 -0.733799385705343 0.6549006077802048
  -0.49434194923946795 0.21885524294941494]
 [0.0 1.7320508075688774 -0.733799385705343 -0.947621483893497
  -1.494179356244993 -0.30512103616996794]
 [0.0 1.7320508075688774 -0.733799385705343 1.770481112122021
  -0.8593266741758989 1.666880795073106]
 [0.0 -0.5773502691896258 1.3627702877384942 0.009617753042540427
  0.17279111579172604 1.2234122937277723]
 [0.0 -0.5773502691896258 1.3627702877384942 -1.1135310904221214
  -2.218961756571209 -0.13669119113063422]
 [0.0 -0.5773502691896258 1.3627702877384942 -0.22790702970059823
  1.1322241571857976 -0.922748838200462]
 [0.0 1.7320508075688774 -0.733799385705343 0.0504700706558041
  -0.023511746780132174 0.819520742715403]
 [0.0 1.7320508075688774 -0.7337993857053

In [ ]:
# Import